# Generated by Django 4.1 on 2022-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banner',
                'db_table': 'banner',
            },
        ),
    ]
